[project]
name = "aoc-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
    "polars>=1.35.2",
    "polars-ds>=0.10.3",
    "pytest>=9.0.1",
    "scipy>=1.16.3",
]

[tool.uv]
package = true
